;; Skeleton des Makefiles
(define-skeleton create-makefile
  "Create a Makefile."
  ""
  "NAME\t= \n"
  "\n"
  "SRCDIR\t= src\n"
  "\n"
  "SRC\t= $(SRCDIR)\\n"
  "\n"
  "LIB\t= -L lib/ -lmy\n"
  "INC\t= -I include/\n"
  "\n"
  "OBJ\t= $(SRC:.c=.o)\n"
  "\n"
  "CC\t= /usr/bin/gcc\n"
  "\n"
  "CFLAGS\t= -W -Wall -Wextra -ansi -pedantic\n"
  "CDEBUG\t= -O2 -g -ggdb\n"
  "\n"
  "RM\t= rm -f\n"
  "ECHO\t= echo -e\n"
  "\n"
  "all\t: $(NAME)\n"
  "\n"
  "$(NAME)\t: $(OBJ)\n"
  "\t@$(CC) $(INC) $(CFLAGS) -o $(NAME) $(OBJ) $(LIB)\n"
  "\t@$(ECHO) '\\033[0;32m> Compiled\\033[0m'\n"
  "\n"
  "clean\t:\n"
  "\t-@$(RM) $(OBJ)\n"
  "\t-@$(RM) *~\n"
  "\t-@$(RM) \\#*\#\n"
  "\t@$(ECHO) '\\033[0;31m> Directory cleaned\\033[0m'\n"
  "\n"
  "\n"
  "fclean\t: clean\n"
  "\t-@$(RM) $(NAME)\n"
  "\t@$(ECHO) '\\033[0;31m> Remove executable\\033[0m'\n"
  "\n"
  "re\t: fclean all\n"
  "\n"
  ".PHONY\t: all clean fclean re\n"
  "\n"
  "debug\t: $(OBJ)\n"
  "\t@$(CC) $(INC) $(CDEBUG) -o $(NAME) $(OBJ) $(LIB)\n"
  "\t@$(ECHO) '\\033[0;33m> Mode Debug: done\\033[0m'\n"
  "\n")
